default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV['DB_POOL'] || ENV['RAILS_MAX_THREADS'] || 5 %>

production:
  <<: *default

staging:
  <<: *default

development:
  <<: *default
  database: omoroi_development
  username: development
  password: omoroi2018

test:
  <<: *default
