production:
  app_host:  omoroi-fe.herokuapp.com
  api_host:  omoroi-be.herokuapp.com

staging:
  app_host:  omoroi-fe-staging.herokuapp.com
  api_host:  omoroi-be-staging.herokuapp.com

development:
  app_host:  192.168.1.6:3000
  api_host:  127.0.0.1:4000
  smtp_host: 127.0.0.1
  smtp_port: 1025
